package atps;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafaelgs
 */
public class jfDiaria extends javax.swing.JFrame {

    private cDados dados = new cDados();
    private DefaultTableModel tm = new DefaultTableModel();
    private DefaultListModel lm = new DefaultListModel();
    private cAluguel aluguel = new cAluguel();
    private cPessoa pessoa = new cPessoa(0, null, null, null, null);
    private cQuarto quarto = new cQuarto(0, null, null, null, null, 0, null);
    private int val;
    private int[] numQuart = new int[99];
    private int i = 0;

    /**
     * Creates new form jfDiaria
     */
    public jfDiaria() {
        System.out.println("APPLOG(jfDiaria.jfDiaria) -> INICIANDO COMPONENTES DA DIARIA");
        initComponents();
        System.out.println("APPLOG(jfDiaria.jfDiaria) -> INICIANDO COMPONENTES DA DIARIA [OK]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoDormitorio = new javax.swing.ButtonGroup();
        btnFechar = new javax.swing.JButton();
        jpnlPaineControle = new javax.swing.JPanel();
        jbtnAdcReg = new javax.swing.JButton();
        jbtnCarrReg = new javax.swing.JButton();
        jbtnRemReg = new javax.swing.JButton();
        jbtnAttReg = new javax.swing.JButton();
        jbtnCalcular = new javax.swing.JButton();
        jpInfoQuarto = new javax.swing.JPanel();
        jlDescQuarto = new javax.swing.JLabel();
        jlNumQuarto = new javax.swing.JLabel();
        jtfDescQuarto = new javax.swing.JTextField();
        jtfNumQuarto = new javax.swing.JTextField();
        jlAndarQuarto = new javax.swing.JLabel();
        jtfAndarQuarto = new javax.swing.JTextField();
        jlTipoQuarto = new javax.swing.JLabel();
        jtfTipoQuarto = new javax.swing.JTextField();
        jlValorQuarto = new javax.swing.JLabel();
        jrbtnQuarto = new javax.swing.JRadioButton();
        jrbtnChale = new javax.swing.JRadioButton();
        jlCamas = new javax.swing.JLabel();
        jcbxNumCamas = new javax.swing.JComboBox();
        jbtnCalcSubTtl = new javax.swing.JButton();
        jlSubVlrTtl = new javax.swing.JLabel();
        jtfValorQuarto = new javax.swing.JFormattedTextField();
        jtfVlrSubTtl = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaNota = new javax.swing.JTextArea();
        jpInfoCliente = new javax.swing.JPanel();
        jlNomeCli = new javax.swing.JLabel();
        jlRGCli = new javax.swing.JLabel();
        jlTelCli = new javax.swing.JLabel();
        jlCPFCli = new javax.swing.JLabel();
        jlDatNascCli = new javax.swing.JLabel();
        jtfNomeCli = new javax.swing.JTextField();
        jtfRGCli = new javax.swing.JFormattedTextField();
        jtfCPFCli = new javax.swing.JFormattedTextField();
        jtfTelCli = new javax.swing.JFormattedTextField();
        jtfDatNasc = new javax.swing.JFormattedTextField();
        jpCalcDiaria = new javax.swing.JPanel();
        jlDatEntrada = new javax.swing.JLabel();
        jlDatSaida = new javax.swing.JLabel();
        jlHorEntrada = new javax.swing.JLabel();
        jlHorSaida = new javax.swing.JLabel();
        jtfHorEntrada = new javax.swing.JFormattedTextField();
        jtfHorSaida = new javax.swing.JFormattedTextField();
        jlDoisPntsI = new javax.swing.JLabel();
        jlDoisPntsII = new javax.swing.JLabel();
        jtfMinEntrada = new javax.swing.JFormattedTextField();
        jtfMinSaida = new javax.swing.JFormattedTextField();
        jlVlrTotal = new javax.swing.JLabel();
        jlRCifrao = new javax.swing.JLabel();
        jlVlrTtlMostra = new javax.swing.JLabel();
        jtfDatEntrada = new javax.swing.JFormattedTextField();
        jtfDatSaida = new javax.swing.JFormattedTextField();
        jpClientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DIARIAS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jpnlPaineControle.setBorder(javax.swing.BorderFactory.createTitledBorder("Painel de Controle"));

        jbtnAdcReg.setText("Adicionar Registro");
        jbtnAdcReg.setToolTipText("Adiciona o Registro à Tabela");
        jbtnAdcReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdcRegActionPerformed(evt);
            }
        });

        jbtnCarrReg.setText("Carregar Registro");
        jbtnCarrReg.setToolTipText("Carrega o Registro SELECIONADO para Edição");
        jbtnCarrReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCarrRegActionPerformed(evt);
            }
        });

        jbtnRemReg.setText("Remover Registro");
        jbtnRemReg.setToolTipText("Remove Registro SELECIONADO");
        jbtnRemReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemRegActionPerformed(evt);
            }
        });

        jbtnAttReg.setText("Atualizar Registro");
        jbtnAttReg.setToolTipText("Atualiza registro SELECIONADO com as informações dos campos");
        jbtnAttReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAttRegActionPerformed(evt);
            }
        });

        jbtnCalcular.setText("Finalizar Hospedagem");
        jbtnCalcular.setToolTipText("Calcula o Valor das Diárias");
        jbtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlPaineControleLayout = new javax.swing.GroupLayout(jpnlPaineControle);
        jpnlPaineControle.setLayout(jpnlPaineControleLayout);
        jpnlPaineControleLayout.setHorizontalGroup(
            jpnlPaineControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPaineControleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnAdcReg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCarrReg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRemReg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAttReg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jbtnCalcular)
                .addContainerGap())
        );
        jpnlPaineControleLayout.setVerticalGroup(
            jpnlPaineControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPaineControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlPaineControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdcReg)
                    .addComponent(jbtnCarrReg)
                    .addComponent(jbtnRemReg)
                    .addComponent(jbtnAttReg)
                    .addComponent(jbtnCalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpInfoQuarto.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Quarto"));
        jpInfoQuarto.setToolTipText("Informações do Quarto");

        jlDescQuarto.setText("Descrição:");

        jlNumQuarto.setText("Nº:");

        jtfDescQuarto.setToolTipText("Descrição do Quarto");

        jtfNumQuarto.setToolTipText("Número do Quarto");
        jtfNumQuarto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumQuartoFocusLost(evt);
            }
        });
        jtfNumQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumQuartoActionPerformed(evt);
            }
        });

        jlAndarQuarto.setText("Andar:");

        jtfAndarQuarto.setToolTipText("Andar do Quarto");

        jlTipoQuarto.setText("Tipo:");

        jtfTipoQuarto.setToolTipText("Tipo de Quarto");
        jtfTipoQuarto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jlValorQuarto.setText("Valor Diaria:");

        jrbtnQuarto.setText("Quarto");
        jrbtnQuarto.setToolTipText("Selecionar tipo Quarto");
        jrbtnQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnQuartoActionPerformed(evt);
            }
        });

        jrbtnChale.setText("Chalé (+ 20%)");
        jrbtnChale.setToolTipText("Selecionar tipo Chalé com aumento de 20% no valor da Diária");
        jrbtnChale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnChaleActionPerformed(evt);
            }
        });

        jlCamas.setText("Camas Adicionais:");

        jcbxNumCamas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1 +10%", "2 +20%", "3 +30%", "4 +40%", "5 +50%" }));
        jcbxNumCamas.setToolTipText("Selecionar quantidade de camas adicionais com aumento de 10% para cada nova cama");

        jbtnCalcSubTtl.setText("Sub-Total Diaria");
        jbtnCalcSubTtl.setToolTipText("Calcular Sub-Total da Diaria");
        jbtnCalcSubTtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcSubTtlActionPerformed(evt);
            }
        });

        jlSubVlrTtl.setText("Sub-Total Diaria:");

        try {
            jtfValorQuarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ *************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfValorQuarto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        try {
            jtfVlrSubTtl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfVlrSubTtl.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpInfoQuartoLayout = new javax.swing.GroupLayout(jpInfoQuarto);
        jpInfoQuarto.setLayout(jpInfoQuartoLayout);
        jpInfoQuartoLayout.setHorizontalGroup(
            jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlValorQuarto)
                    .addComponent(jlTipoQuarto)
                    .addComponent(jlDescQuarto)
                    .addComponent(jlNumQuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                        .addComponent(jtfDescQuarto)
                        .addContainerGap())
                    .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                        .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                                .addComponent(jtfValorQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jbtnCalcSubTtl)
                                .addGap(18, 18, 18)
                                .addComponent(jlSubVlrTtl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfVlrSubTtl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfTipoQuarto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNumQuarto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                                        .addComponent(jlAndarQuarto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfAndarQuarto))
                                    .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                                        .addComponent(jrbtnQuarto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbtnChale)))
                                .addGap(18, 18, 18)
                                .addComponent(jlCamas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbxNumCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpInfoQuartoLayout.setVerticalGroup(
            jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescQuarto)
                    .addComponent(jtfDescQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumQuarto)
                    .addComponent(jtfNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAndarQuarto)
                    .addComponent(jtfAndarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoQuarto)
                    .addComponent(jtfTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtnQuarto)
                    .addComponent(jrbtnChale)
                    .addComponent(jlCamas)
                    .addComponent(jcbxNumCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorQuarto)
                    .addComponent(jbtnCalcSubTtl)
                    .addComponent(jlSubVlrTtl)
                    .addComponent(jtfValorQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVlrSubTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxaNota.setColumns(20);
        jtxaNota.setRows(5);
        jtxaNota.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtxaNota.setPreferredSize(new java.awt.Dimension(164, 117));
        jScrollPane1.setViewportView(jtxaNota);

        jpInfoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Cliente"));
        jpInfoCliente.setToolTipText("Informações do Cliente");

        jlNomeCli.setText("Nome:");

        jlRGCli.setText("RG:");

        jlTelCli.setText("Tel:");

        jlCPFCli.setText("CPF:");

        jlDatNascCli.setText("Data Nasc.:");

        jtfNomeCli.setToolTipText("Nome do Cliente");

        try {
            jtfRGCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtfCPFCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtfTelCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtfDatNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpInfoClienteLayout = new javax.swing.GroupLayout(jpInfoCliente);
        jpInfoCliente.setLayout(jpInfoClienteLayout);
        jpInfoClienteLayout.setHorizontalGroup(
            jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTelCli)
                    .addComponent(jlRGCli)
                    .addComponent(jlNomeCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInfoClienteLayout.createSequentialGroup()
                        .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfRGCli)
                            .addComponent(jtfTelCli, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInfoClienteLayout.createSequentialGroup()
                                .addComponent(jlDatNascCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDatNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                            .addGroup(jpInfoClienteLayout.createSequentialGroup()
                                .addComponent(jlCPFCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCPFCli))))
                    .addComponent(jtfNomeCli))
                .addContainerGap())
        );
        jpInfoClienteLayout.setVerticalGroup(
            jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeCli)
                    .addComponent(jtfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRGCli)
                    .addComponent(jlCPFCli)
                    .addComponent(jtfRGCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelCli)
                    .addComponent(jlDatNascCli)
                    .addComponent(jtfTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDatNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpCalcDiaria.setBorder(javax.swing.BorderFactory.createTitledBorder("Diaria"));
        jpCalcDiaria.setToolTipText("Calculo da Diaria");
        jpCalcDiaria.setPreferredSize(new java.awt.Dimension(351, 117));

        jlDatEntrada.setText("Data Entrada:");

        jlDatSaida.setText("Data Saída:");

        jlHorEntrada.setText("Hora Entrada:");

        jlHorSaida.setText("Hora Saída:");

        try {
            jtfHorEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfHorEntrada.setToolTipText("Hora de Entrada do Cliente");
        jtfHorEntrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfHorEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfHorEntradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfHorEntradaFocusLost(evt);
            }
        });

        try {
            jtfHorSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfHorSaida.setToolTipText("Hora de Saída do Cliente");
        jtfHorSaida.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfHorSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfHorSaidaFocusGained(evt);
            }
        });
        jtfHorSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHorSaidaActionPerformed(evt);
            }
        });

        jlDoisPntsI.setText(":");

        jlDoisPntsII.setText(":");

        try {
            jtfMinEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfMinEntrada.setToolTipText("Minutos de Entrada do Cliente");
        jtfMinEntrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfMinEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfMinEntradaFocusGained(evt);
            }
        });

        try {
            jtfMinSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfMinSaida.setToolTipText("Minutos de Saída do Cliente");
        jtfMinSaida.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfMinSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfMinSaidaFocusGained(evt);
            }
        });
        jtfMinSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinSaidaActionPerformed(evt);
            }
        });

        jlVlrTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlVlrTotal.setForeground(new java.awt.Color(255, 0, 0));
        jlVlrTotal.setText("TOTAL:");

        jlRCifrao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlRCifrao.setText("R$");

        jlVlrTtlMostra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlVlrTtlMostra.setToolTipText("Preço a ser pago!");

        try {
            jtfDatEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDatEntrada.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        try {
            jtfDatSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDatSaida.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpCalcDiariaLayout = new javax.swing.GroupLayout(jpCalcDiaria);
        jpCalcDiaria.setLayout(jpCalcDiariaLayout);
        jpCalcDiariaLayout.setHorizontalGroup(
            jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                        .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlDatSaida)
                            .addComponent(jlDatEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDatEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jtfDatSaida))
                        .addGap(18, 18, 18)
                        .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlHorEntrada)
                            .addComponent(jlHorSaida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfHorEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jtfHorSaida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                                .addComponent(jlDoisPntsI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMinEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                                .addComponent(jlDoisPntsII)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMinSaida)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                        .addComponent(jlVlrTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlRCifrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlVlrTtlMostra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpCalcDiariaLayout.setVerticalGroup(
            jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCalcDiariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDatEntrada)
                    .addComponent(jlHorEntrada)
                    .addComponent(jtfHorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDoisPntsI)
                    .addComponent(jtfMinEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDatEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDatSaida)
                    .addComponent(jlHorSaida)
                    .addComponent(jtfHorSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDoisPntsII)
                    .addComponent(jtfMinSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDatSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCalcDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlVlrTotal)
                        .addComponent(jlRCifrao))
                    .addComponent(jlVlrTtlMostra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jpClientes.setToolTipText("Lista de Clientes");
        jpClientes.setName("jpClientes"); // NOI18N

        jtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nome do Cliente", "Valor Inicial da Diaria ", "Data de Entrada ", "CPF do Cliente", "Telefone do Cliente", "RG do Cliente", "Data Nascimento", "Descrição do Quarto", "Numero do Quarto ", "Andar do Quarto ", "Tipo de Quarto ", "Hora de Entrada  ", "Minutos de Entrada ", "Quantidade de Camas", "Valor Total da Diaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jtTable);

        javax.swing.GroupLayout jpClientesLayout = new javax.swing.GroupLayout(jpClientes);
        jpClientes.setLayout(jpClientesLayout);
        jpClientesLayout.setHorizontalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jpClientesLayout.setVerticalGroup(
            jpClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlPaineControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpInfoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpCalcDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                            .addComponent(jpInfoQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpCalcDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jpInfoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpInfoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jpnlPaineControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        revES();
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void jbtnAdcRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdcRegActionPerformed
        // TODO add your handling code here:
        int ii = 0;
        try {
            ii = verQuarto(Integer.valueOf(jtfNumQuarto.getText()));
        } catch (NullPointerException ex) {
            System.out.println("Numero do quarto está vazio");
            ii = 0;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Numero do quarto está vazio!!!");
            ii = 0;
        }

        if (ii == 1) {
            enviaDados(evt);
            enviaTDados();
            JOptionPane.showMessageDialog(null, "Registro adicionado com sucesso!");
        }


    }//GEN-LAST:event_jbtnAdcRegActionPerformed

    private void jbtnCarrRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCarrRegActionPerformed
        // TODO add your handling code here:

        try {
            //REGISTRO DE ENTRADA
            jtfHorEntrada.setText((String) modTabela().getValueAt(selLinha(), 12));
            jtfMinEntrada.setText((String) modTabela().getValueAt(selLinha(), 13));
            jtfDatEntrada.setText((String) modTabela().getValueAt(selLinha(), 3));

            //CLIENTE
            jtfNomeCli.setText((String) modTabela().getValueAt(selLinha(), 1));
            jtfRGCli.setText((String) modTabela().getValueAt(selLinha(), 6));
            jtfCPFCli.setText((String) modTabela().getValueAt(selLinha(), 4));
            jtfTelCli.setText((String) modTabela().getValueAt(selLinha(), 5));
            jtfDatNasc.setText((String) modTabela().getValueAt(selLinha(), 7));

            //QUARTO
            jtfDescQuarto.setText((String) modTabela().getValueAt(selLinha(), 8));
            jtfNumQuarto.setText((String) modTabela().getValueAt(selLinha(), 9));
            jtfAndarQuarto.setText((String) modTabela().getValueAt(selLinha(), 10));
            jtfTipoQuarto.setText((String) modTabela().getValueAt(selLinha(), 11));
            jtfValorQuarto.setText((String) modTabela().getValueAt(selLinha(), 2));
            jtfVlrSubTtl.setText((String) modTabela().getValueAt(selLinha(), 15));
            jcbxNumCamas.setSelectedIndex((int) modTabela().getValueAt(selLinha(), 14));
        } catch (NullPointerException ex) {
            System.out.println("Existe algum valor vazio!!!");
        } catch (ClassCastException ex) {

        }

        JOptionPane.showMessageDialog(null, "Informações carregadas com sucesso!");
    }//GEN-LAST:event_jbtnCarrRegActionPerformed

    private void jbtnRemRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemRegActionPerformed
        // TODO add your handling code here:
        removeLinha(selLinha());
        JOptionPane.showMessageDialog(null, "Registro Eliminado com sucesso!");
    }//GEN-LAST:event_jbtnRemRegActionPerformed

    private void jbtnAttRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAttRegActionPerformed
        // TODO add your handling code here:
        //CLIENTE
        modTabela().setValueAt(jtfNomeCli.getText(), selLinha(), 1);
        modTabela().setValueAt(jtfRGCli.getText(), selLinha(), 6);
        modTabela().setValueAt(jtfCPFCli.getText(), selLinha(), 4);
        modTabela().setValueAt(jtfTelCli.getText(), selLinha(), 5);
        modTabela().setValueAt(jtfDatNasc.getText(), selLinha(), 7);

        //QUARTO
        modTabela().setValueAt(jtfDescQuarto.getText(), selLinha(), 8);
        modTabela().setValueAt(jtfNumQuarto.getText(), selLinha(), 9);
        modTabela().setValueAt(jtfAndarQuarto.getText(), selLinha(), 10);
        modTabela().setValueAt(jtfTipoQuarto.getText(), selLinha(), 11);
        modTabela().setValueAt(jtfValorQuarto.getText(), selLinha(), 2);
        modTabela().setValueAt(jtfVlrSubTtl.getText(), selLinha(), 15);
        modTabela().setValueAt(jcbxNumCamas.getSelectedIndex(), selLinha(), 14);

        //REGISTRO DE ENTRADA
        modTabela().setValueAt(jtfHorEntrada.getText(), selLinha(), 12);
        modTabela().setValueAt(jtfMinEntrada.getText(), selLinha(), 13);
        modTabela().setValueAt(jtfDatEntrada.getText(), selLinha(), 3);

        JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso!");
    }//GEN-LAST:event_jbtnAttRegActionPerformed

    private void jbtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcularActionPerformed
        // TODO add your handling code here:
        BigDecimal aux0 = new BigDecimal("00.00");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // CALCULO DOS DIAS
        try {
            aluguel.calc_diaria_dia(sdf.parse(jtfDatEntrada.getText()),
                    sdf.parse(jtfDatSaida.getText()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Favor revisar as datas");
        }
        // CALCULO DAS HORAS
        aluguel.calc_diaria_hora((jtfHorEntrada.getText()
                + jtfMinEntrada.getText()), (jtfHorSaida.getText() + jtfMinSaida.getText()));
        //CALCULO DO VALOR
        aux0 = (new BigDecimal(aluguel.getDiarias1())).multiply(new BigDecimal(jtfVlrSubTtl.getText().replaceAll("R", "").replaceAll(" ", "").replace("$", "")));
        //EXIBIÇÃO DO VALOR TOTAL
        jlVlrTtlMostra.setText(String.valueOf(aux0));
        //EXIBIÇÃO DO RECIBO
        jtxaNota.setText("========================================"
                + "\nLocatário: " + modTabela().getValueAt(selLinha(), 1)
                + "\nData e horário de entrada: " + jtfDatEntrada.getText() + " | "
                + (jtfHorEntrada.getText() + ":" + jtfMinEntrada.getText())
                + "\nData e horário de saída: " + jtfDatSaida.getText() + " | "
                + (jtfHorSaida.getText() + ":" + jtfMinSaida.getText())
                + "\nNumero de diarias: " + aluguel.getDiarias1()
                + "\nTotal devido: R$" + aux0
                + "\n========================================");
    }//GEN-LAST:event_jbtnCalcularActionPerformed

    private void jtfNumQuartoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumQuartoFocusLost
        // TODO add your handling code here:
        int aux = Integer.valueOf(jtfNumQuarto.getText());
        if (aux <= 50 && aux >= 1) {
            jrbtnQuartoActionPerformed(null);
            jrbtnQuarto.doClick();
        } else if (aux > 60) {
            JOptionPane.showMessageDialog(null, "Não esxite essa quantidade de quartos!!!"
                    + "\nFavor corrigir Número do Quarto, escolha entre 1 e 60"
                    + "\n1 a 50 Quarto"
                    + "\n51 a 60 Chalé");
        } else {
            jrbtnChaleActionPerformed(null);
            jrbtnChale.doClick();
        }
    }//GEN-LAST:event_jtfNumQuartoFocusLost

    private void jtfNumQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumQuartoActionPerformed

    private void jrbtnQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnQuartoActionPerformed
        // TODO add your handling code here:
        jtfTipoQuarto.setText("Quarto");
    }//GEN-LAST:event_jrbtnQuartoActionPerformed

    private void jrbtnChaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnChaleActionPerformed
        // TODO add your handling code here:
        jtfTipoQuarto.setText("Chalé");
    }//GEN-LAST:event_jrbtnChaleActionPerformed

    private void jbtnCalcSubTtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcSubTtlActionPerformed
        // TODO add your handling code here:

        String opcQtdC = "00.00";
        String opcCha = "00.00";
        String opc;

        switch (jcbxNumCamas.getSelectedIndex()) {

            case 0:
                opcQtdC = "00.00";
                break;
            case 1:
                opcQtdC = "00.10";
                break;
            case 2:
                opcQtdC = "00.20";
                break;
            case 3:
                opcQtdC = "00.30";
                break;
            case 4:
                opcQtdC = "00.40";
                break;
            case 5:
                opcQtdC = "00.50";
                break;

        }

        switch (jtfTipoQuarto.getText()) {

            case "Chalé":
                opcCha = "00.20";
                break;
            case "Quarto":
                opcCha = "00.00";
                break;

        }

        jtfVlrSubTtl.setText(String.valueOf(aluguel.calc_sub_ttl(jtfValorQuarto.getText().replaceAll("R", "").replaceAll(" ", "").replace("$", ""), opcQtdC, opcCha)));
    }//GEN-LAST:event_jbtnCalcSubTtlActionPerformed

    private void jtfHorEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfHorEntradaFocusGained
        // TODO add your handling code here:
        jtfHorEntrada.setText(null);
    }//GEN-LAST:event_jtfHorEntradaFocusGained

    private void jtfHorSaidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfHorSaidaFocusGained
        // TODO add your handling code here:
        jtfHorSaida.setText(null);
    }//GEN-LAST:event_jtfHorSaidaFocusGained

    private void jtfHorSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHorSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHorSaidaActionPerformed

    private void jtfMinEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMinEntradaFocusGained
        // TODO add your handling code here:
        jtfMinEntrada.setText(null);
    }//GEN-LAST:event_jtfMinEntradaFocusGained

    private void jtfMinSaidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMinSaidaFocusGained
        // TODO add your handling code here:
        jtfMinSaida.setText(null);
    }//GEN-LAST:event_jtfMinSaidaFocusGained

    private void jtfMinSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMinSaidaActionPerformed

    private void jtfHorEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfHorEntradaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHorEntradaFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfDiaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfDiaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfDiaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfDiaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfDiaria().setVisible(true);
            }
        });
    }

    public void regEntrada() {
        jtfDatSaida.setEnabled(false);
        jtfHorSaida.setEnabled(false);
        jtfMinSaida.setEnabled(false);
        jbtnCalcular.setEnabled(false);
        jtfValorQuarto.setEnabled(false);
        jtfVlrSubTtl.setEnabled(false);
        jtfTipoQuarto.setEnabled(false);
        jtxaNota.setEnabled(false);
    }

    public void regSaida() {
        jtfDatEntrada.setEnabled(false);
        jtfHorEntrada.setEnabled(false);
        jtfMinEntrada.setEnabled(false);
        jbtnAdcReg.setEnabled(false);
        jtfValorQuarto.setEnabled(false);
        jtfVlrSubTtl.setEnabled(false);
        jtfTipoQuarto.setEnabled(false);
        jtxaNota.setEnabled(false);
    }

    public void revES() {
        jtfDatSaida.setEnabled(true);
        jtfHorSaida.setEnabled(true);
        jtfMinSaida.setEnabled(true);
        jbtnCalcular.setEnabled(true);
        jtfDatEntrada.setEnabled(true);
        jtfHorEntrada.setEnabled(true);
        jtfMinEntrada.setEnabled(true);
        jbtnAdcReg.setEnabled(true);
        jbtnRemReg.setEnabled(true);

        //CLIENTE
        jtfNomeCli.setText(null);
        jtfRGCli.setText(null);
        jtfCPFCli.setText(null);
        jtfTelCli.setText(null);
        jtfDatNasc.setText(null);

        //QUARTO
        jtfDescQuarto.setText(null);
        jtfNumQuarto.setText(null);
        jtfAndarQuarto.setText(null);
        jtfTipoQuarto.setText(null);
        jtfValorQuarto.setText(null);
        jtfVlrSubTtl.setText(null);
        jcbxNumCamas.setSelectedIndex(0);
        jrbtnChale.setSelected(false);
        jrbtnQuarto.setSelected(false);
        jlVlrTtlMostra.setText(null);

        //REGISTRO DE ENTRADA
        jtfHorEntrada.setText(null);
        jtfMinEntrada.setText(null);
        jtfDatEntrada.setText(null);

        //REGISTRO DE SAIDA
        jtfHorSaida.setText(null);
        jtfMinSaida.setText(null);
        jtfDatSaida.setText(null);

        //NOTA
        jtxaNota.setText(null);

    }

    public void entVlrPadr(String valor) {
        jtfValorQuarto.setText(valor);
    }

    public int selLinha() {
        int ls = jtTable.getSelectedRow();

        if (ls < 0) {
            JOptionPane.showMessageDialog(null, "Nenhum Registro foi selecionado!!!"
                    + "\nFavor clicar em um registro na tabela acima.");
        }

        return ls;
    }

    public DefaultTableModel modTabela() {
        tm = (DefaultTableModel) jtTable.getModel();
        return tm;
    }

    public void removeLinha(int linha) {

        tm = (DefaultTableModel) jtTable.getModel();
        tm.removeRow(linha);

    }

    public int enviaDados(java.awt.event.ActionEvent evt) {

        try {
            int val = 0;
            int[] val2 = new int[5];

            BigDecimal aux0 = new BigDecimal("00.00");
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            //INFORMAÇÕES DO CLIENTE
            try {
                pessoa = new cPessoa(
                        dados.numInfo(),
                        jtfNomeCli.getText(),
                        jtfRGCli.getText(),
                        jtfCPFCli.getText(),
                        jtfTelCli.getText()
                );
                try {
                    pessoa.setDatanasc(sdf.parse(jtfDatNasc.getText()));
                    val2[2] = 1;
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Favor revisar a data de nascimento");
                    val2[2] = 0;
                }
                val2[1] = 1;
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
                val2[1] = 0;
            }

            try {

                quarto = new cQuarto(
                        dados.numInfoQ(),
                        jtfDescQuarto.getText(),
                        jtfNumQuarto.getText(),
                        jtfAndarQuarto.getText(),
                        jtfTipoQuarto.getText(),
                        (dados.numInfo() - 1),
                        null
                );
                try {
                    jbtnCalcSubTtlActionPerformed(evt);
                    quarto.setValor_quarto(new BigDecimal(jtfVlrSubTtl.getText().replaceAll("R", "").replaceAll(" ", "").replace("$", "")));
                    val2[4] = 1;
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Favor inserir no formato demonstrado no exemplo \nXX.XX");
                    val2[4] = 0;
                }
                val2[3] = 1;
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
                val2[3] = 0;
            }

            //INSERE AS INFORMAÇOS NA LISTA
            dados.cadInfo(pessoa);
            dados.cadInfoQ(quarto);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Existem campos vazios!!!");
        }

        return val = 1;
    }

    public int verQuarto(int qrtAtl) {

        int ret = 1;

        for (int i = 0; i < jtTable.getRowCount(); i++) {

            int aux;
            aux = Integer.valueOf(jtTable.getValueAt(i, 9).toString());
            if (aux == qrtAtl) {
                ret = 0;
                JOptionPane.showMessageDialog(null, "Quarto em uso!!!");
            }

        }
        return ret;

    }

    public void enviaTDados() {

        String aux9 = Integer.toString(dados.numInfo());
        String aux10 = Integer.toString(jcbxNumCamas.getSelectedIndex());
        modTabela().addRow(new String[]{
            aux9,
            jtfNomeCli.getText(),
            jtfValorQuarto.getText(),
            jtfDatEntrada.getText(),
            jtfCPFCli.getText(),
            jtfTelCli.getText(),
            jtfRGCli.getText(),
            jtfDatNasc.getText(),
            jtfDescQuarto.getText(),
            jtfNumQuarto.getText(),
            jtfAndarQuarto.getText(),
            jtfTipoQuarto.getText(),
            jtfHorEntrada.getText(),
            jtfMinEntrada.getText(),
            aux10,
            jtfVlrSubTtl.getText()
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup btngTipoDormitorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnAdcReg;
    private javax.swing.JButton jbtnAttReg;
    private javax.swing.JButton jbtnCalcSubTtl;
    private javax.swing.JButton jbtnCalcular;
    private javax.swing.JButton jbtnCarrReg;
    private javax.swing.JButton jbtnRemReg;
    private javax.swing.JComboBox jcbxNumCamas;
    private javax.swing.JLabel jlAndarQuarto;
    private javax.swing.JLabel jlCPFCli;
    private javax.swing.JLabel jlCamas;
    private javax.swing.JLabel jlDatEntrada;
    private javax.swing.JLabel jlDatNascCli;
    private javax.swing.JLabel jlDatSaida;
    private javax.swing.JLabel jlDescQuarto;
    private javax.swing.JLabel jlDoisPntsI;
    private javax.swing.JLabel jlDoisPntsII;
    private javax.swing.JLabel jlHorEntrada;
    private javax.swing.JLabel jlHorSaida;
    private javax.swing.JLabel jlNomeCli;
    private javax.swing.JLabel jlNumQuarto;
    private javax.swing.JLabel jlRCifrao;
    private javax.swing.JLabel jlRGCli;
    private javax.swing.JLabel jlSubVlrTtl;
    private javax.swing.JLabel jlTelCli;
    private javax.swing.JLabel jlTipoQuarto;
    private javax.swing.JLabel jlValorQuarto;
    private javax.swing.JLabel jlVlrTotal;
    private javax.swing.JLabel jlVlrTtlMostra;
    private javax.swing.JPanel jpCalcDiaria;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpInfoCliente;
    private javax.swing.JPanel jpInfoQuarto;
    private javax.swing.JPanel jpnlPaineControle;
    private javax.swing.JRadioButton jrbtnChale;
    private javax.swing.JRadioButton jrbtnQuarto;
    private javax.swing.JTable jtTable;
    private javax.swing.JTextField jtfAndarQuarto;
    private javax.swing.JFormattedTextField jtfCPFCli;
    private javax.swing.JFormattedTextField jtfDatEntrada;
    private javax.swing.JFormattedTextField jtfDatNasc;
    private javax.swing.JFormattedTextField jtfDatSaida;
    private javax.swing.JTextField jtfDescQuarto;
    private javax.swing.JFormattedTextField jtfHorEntrada;
    private javax.swing.JFormattedTextField jtfHorSaida;
    private javax.swing.JFormattedTextField jtfMinEntrada;
    private javax.swing.JFormattedTextField jtfMinSaida;
    private javax.swing.JTextField jtfNomeCli;
    private javax.swing.JTextField jtfNumQuarto;
    private javax.swing.JFormattedTextField jtfRGCli;
    private javax.swing.JFormattedTextField jtfTelCli;
    private javax.swing.JTextField jtfTipoQuarto;
    private javax.swing.JFormattedTextField jtfValorQuarto;
    private javax.swing.JFormattedTextField jtfVlrSubTtl;
    private javax.swing.JTextArea jtxaNota;
    // End of variables declaration//GEN-END:variables

    public cDados getDados() {
        return dados;
    }

    public void setDados(cDados dados) {
        this.dados = dados;
    }

    public DefaultTableModel getTm() {
        return tm;
    }

    public void setTm(DefaultTableModel tm) {
        this.tm = tm;
    }

    public DefaultListModel getLm() {
        return lm;
    }

    public void setLm(DefaultListModel lm) {
        this.lm = lm;
    }

    public cAluguel getAluguel() {
        return aluguel;
    }

    public void setAluguel(cAluguel aluguel) {
        this.aluguel = aluguel;
    }

    public cPessoa getPessoa() {
        return pessoa;
    }

    public void setPessoa(cPessoa pessoa) {
        this.pessoa = pessoa;
    }

    public cQuarto getQuarto() {
        return quarto;
    }

    public void setQuarto(cQuarto quarto) {
        this.quarto = quarto;
    }

    public int getVal() {
        return val;
    }

    public void setVal(int val) {
        this.val = val;
    }

    public int[] getNumQuart() {
        return numQuart;
    }

    public void setNumQuart(int[] numQuart) {
        this.numQuart = numQuart;
    }

    public int getI() {
        return i;
    }

    public void setI(int i) {
        this.i = i;
    }

    public javax.swing.JButton getBtnFechar() {
        return btnFechar;
    }

    public void setBtnFechar(javax.swing.JButton btnFechar) {
        this.btnFechar = btnFechar;
    }

    public javax.swing.ButtonGroup getBtngTipoDormitorio() {
        return btngTipoDormitorio;
    }

    public void setBtngTipoDormitorio(javax.swing.ButtonGroup btngTipoDormitorio) {
        this.btngTipoDormitorio = btngTipoDormitorio;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(javax.swing.JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public javax.swing.JButton getJbtnAdcReg() {
        return jbtnAdcReg;
    }

    public void setJbtnAdcReg(javax.swing.JButton jbtnAdcReg) {
        this.jbtnAdcReg = jbtnAdcReg;
    }

    public javax.swing.JButton getJbtnAttReg() {
        return jbtnAttReg;
    }

    public void setJbtnAttReg(javax.swing.JButton jbtnAttReg) {
        this.jbtnAttReg = jbtnAttReg;
    }

    public javax.swing.JButton getJbtnCalcSubTtl() {
        return jbtnCalcSubTtl;
    }

    public void setJbtnCalcSubTtl(javax.swing.JButton jbtnCalcSubTtl) {
        this.jbtnCalcSubTtl = jbtnCalcSubTtl;
    }

    public javax.swing.JButton getJbtnCalcular() {
        return jbtnCalcular;
    }

    public void setJbtnCalcular(javax.swing.JButton jbtnCalcular) {
        this.jbtnCalcular = jbtnCalcular;
    }

    public javax.swing.JButton getJbtnCarrReg() {
        return jbtnCarrReg;
    }

    public void setJbtnCarrReg(javax.swing.JButton jbtnCarrReg) {
        this.jbtnCarrReg = jbtnCarrReg;
    }

    public javax.swing.JButton getJbtnRemReg() {
        return jbtnRemReg;
    }

    public void setJbtnRemReg(javax.swing.JButton jbtnRemReg) {
        this.jbtnRemReg = jbtnRemReg;
    }

    public javax.swing.JComboBox getJcbxNumCamas() {
        return jcbxNumCamas;
    }

    public void setJcbxNumCamas(javax.swing.JComboBox jcbxNumCamas) {
        this.jcbxNumCamas = jcbxNumCamas;
    }

    public javax.swing.JLabel getJlAndarQuarto() {
        return jlAndarQuarto;
    }

    public void setJlAndarQuarto(javax.swing.JLabel jlAndarQuarto) {
        this.jlAndarQuarto = jlAndarQuarto;
    }

    public javax.swing.JLabel getJlCPFCli() {
        return jlCPFCli;
    }

    public void setJlCPFCli(javax.swing.JLabel jlCPFCli) {
        this.jlCPFCli = jlCPFCli;
    }

    public javax.swing.JLabel getJlCamas() {
        return jlCamas;
    }

    public void setJlCamas(javax.swing.JLabel jlCamas) {
        this.jlCamas = jlCamas;
    }

    public javax.swing.JLabel getJlDatEntrada() {
        return jlDatEntrada;
    }

    public void setJlDatEntrada(javax.swing.JLabel jlDatEntrada) {
        this.jlDatEntrada = jlDatEntrada;
    }

    public javax.swing.JLabel getJlDatNascCli() {
        return jlDatNascCli;
    }

    public void setJlDatNascCli(javax.swing.JLabel jlDatNascCli) {
        this.jlDatNascCli = jlDatNascCli;
    }

    public javax.swing.JLabel getJlDatSaida() {
        return jlDatSaida;
    }

    public void setJlDatSaida(javax.swing.JLabel jlDatSaida) {
        this.jlDatSaida = jlDatSaida;
    }

    public javax.swing.JLabel getJlDescQuarto() {
        return jlDescQuarto;
    }

    public void setJlDescQuarto(javax.swing.JLabel jlDescQuarto) {
        this.jlDescQuarto = jlDescQuarto;
    }

    public javax.swing.JLabel getJlDoisPntsI() {
        return jlDoisPntsI;
    }

    public void setJlDoisPntsI(javax.swing.JLabel jlDoisPntsI) {
        this.jlDoisPntsI = jlDoisPntsI;
    }

    public javax.swing.JLabel getJlDoisPntsII() {
        return jlDoisPntsII;
    }

    public void setJlDoisPntsII(javax.swing.JLabel jlDoisPntsII) {
        this.jlDoisPntsII = jlDoisPntsII;
    }

    public javax.swing.JLabel getJlHorEntrada() {
        return jlHorEntrada;
    }

    public void setJlHorEntrada(javax.swing.JLabel jlHorEntrada) {
        this.jlHorEntrada = jlHorEntrada;
    }

    public javax.swing.JLabel getJlHorSaida() {
        return jlHorSaida;
    }

    public void setJlHorSaida(javax.swing.JLabel jlHorSaida) {
        this.jlHorSaida = jlHorSaida;
    }

    public javax.swing.JLabel getJlNomeCli() {
        return jlNomeCli;
    }

    public void setJlNomeCli(javax.swing.JLabel jlNomeCli) {
        this.jlNomeCli = jlNomeCli;
    }

    public javax.swing.JLabel getJlNumQuarto() {
        return jlNumQuarto;
    }

    public void setJlNumQuarto(javax.swing.JLabel jlNumQuarto) {
        this.jlNumQuarto = jlNumQuarto;
    }

    public javax.swing.JLabel getJlRCifrao() {
        return jlRCifrao;
    }

    public void setJlRCifrao(javax.swing.JLabel jlRCifrao) {
        this.jlRCifrao = jlRCifrao;
    }

    public javax.swing.JLabel getJlRGCli() {
        return jlRGCli;
    }

    public void setJlRGCli(javax.swing.JLabel jlRGCli) {
        this.jlRGCli = jlRGCli;
    }

    public javax.swing.JLabel getJlSubVlrTtl() {
        return jlSubVlrTtl;
    }

    public void setJlSubVlrTtl(javax.swing.JLabel jlSubVlrTtl) {
        this.jlSubVlrTtl = jlSubVlrTtl;
    }

    public javax.swing.JLabel getJlTelCli() {
        return jlTelCli;
    }

    public void setJlTelCli(javax.swing.JLabel jlTelCli) {
        this.jlTelCli = jlTelCli;
    }

    public javax.swing.JLabel getJlTipoQuarto() {
        return jlTipoQuarto;
    }

    public void setJlTipoQuarto(javax.swing.JLabel jlTipoQuarto) {
        this.jlTipoQuarto = jlTipoQuarto;
    }

    public javax.swing.JLabel getJlValorQuarto() {
        return jlValorQuarto;
    }

    public void setJlValorQuarto(javax.swing.JLabel jlValorQuarto) {
        this.jlValorQuarto = jlValorQuarto;
    }

    public javax.swing.JLabel getJlVlrTotal() {
        return jlVlrTotal;
    }

    public void setJlVlrTotal(javax.swing.JLabel jlVlrTotal) {
        this.jlVlrTotal = jlVlrTotal;
    }

    public javax.swing.JLabel getJlVlrTtlMostra() {
        return jlVlrTtlMostra;
    }

    public void setJlVlrTtlMostra(javax.swing.JLabel jlVlrTtlMostra) {
        this.jlVlrTtlMostra = jlVlrTtlMostra;
    }

    public javax.swing.JPanel getJpCalcDiaria() {
        return jpCalcDiaria;
    }

    public void setJpCalcDiaria(javax.swing.JPanel jpCalcDiaria) {
        this.jpCalcDiaria = jpCalcDiaria;
    }

    public javax.swing.JPanel getJpClientes() {
        return jpClientes;
    }

    public void setJpClientes(javax.swing.JPanel jpClientes) {
        this.jpClientes = jpClientes;
    }

    public javax.swing.JPanel getJpInfoCliente() {
        return jpInfoCliente;
    }

    public void setJpInfoCliente(javax.swing.JPanel jpInfoCliente) {
        this.jpInfoCliente = jpInfoCliente;
    }

    public javax.swing.JPanel getJpInfoQuarto() {
        return jpInfoQuarto;
    }

    public void setJpInfoQuarto(javax.swing.JPanel jpInfoQuarto) {
        this.jpInfoQuarto = jpInfoQuarto;
    }

    public javax.swing.JPanel getJpnlPaineControle() {
        return jpnlPaineControle;
    }

    public void setJpnlPaineControle(javax.swing.JPanel jpnlPaineControle) {
        this.jpnlPaineControle = jpnlPaineControle;
    }

    public javax.swing.JRadioButton getJrbtnChale() {
        return jrbtnChale;
    }

    public void setJrbtnChale(javax.swing.JRadioButton jrbtnChale) {
        this.jrbtnChale = jrbtnChale;
    }

    public javax.swing.JRadioButton getJrbtnQuarto() {
        return jrbtnQuarto;
    }

    public void setJrbtnQuarto(javax.swing.JRadioButton jrbtnQuarto) {
        this.jrbtnQuarto = jrbtnQuarto;
    }

    public javax.swing.JTable getJtTable() {
        return jtTable;
    }

    public void setJtTable(javax.swing.JTable jtTable) {
        this.jtTable = jtTable;
    }

    public javax.swing.JTextField getJtfAndarQuarto() {
        return jtfAndarQuarto;
    }

    public void setJtfAndarQuarto(javax.swing.JTextField jtfAndarQuarto) {
        this.jtfAndarQuarto = jtfAndarQuarto;
    }

    public javax.swing.JFormattedTextField getJtfCPFCli() {
        return jtfCPFCli;
    }

    public void setJtfCPFCli(javax.swing.JFormattedTextField jtfCPFCli) {
        this.jtfCPFCli = jtfCPFCli;
    }

    public javax.swing.JFormattedTextField getJtfDatEntrada() {
        return jtfDatEntrada;
    }

    public void setJtfDatEntrada(javax.swing.JFormattedTextField jtfDatEntrada) {
        this.jtfDatEntrada = jtfDatEntrada;
    }

    public javax.swing.JFormattedTextField getJtfDatNasc() {
        return jtfDatNasc;
    }

    public void setJtfDatNasc(javax.swing.JFormattedTextField jtfDatNasc) {
        this.jtfDatNasc = jtfDatNasc;
    }

    public javax.swing.JFormattedTextField getJtfDatSaida() {
        return jtfDatSaida;
    }

    public void setJtfDatSaida(javax.swing.JFormattedTextField jtfDatSaida) {
        this.jtfDatSaida = jtfDatSaida;
    }

    public javax.swing.JTextField getJtfDescQuarto() {
        return jtfDescQuarto;
    }

    public void setJtfDescQuarto(javax.swing.JTextField jtfDescQuarto) {
        this.jtfDescQuarto = jtfDescQuarto;
    }

    public javax.swing.JFormattedTextField getJtfHorEntrada() {
        return jtfHorEntrada;
    }

    public void setJtfHorEntrada(javax.swing.JFormattedTextField jtfHorEntrada) {
        this.jtfHorEntrada = jtfHorEntrada;
    }

    public javax.swing.JFormattedTextField getJtfHorSaida() {
        return jtfHorSaida;
    }

    public void setJtfHorSaida(javax.swing.JFormattedTextField jtfHorSaida) {
        this.jtfHorSaida = jtfHorSaida;
    }

    public javax.swing.JFormattedTextField getJtfMinEntrada() {
        return jtfMinEntrada;
    }

    public void setJtfMinEntrada(javax.swing.JFormattedTextField jtfMinEntrada) {
        this.jtfMinEntrada = jtfMinEntrada;
    }

    public javax.swing.JFormattedTextField getJtfMinSaida() {
        return jtfMinSaida;
    }

    public void setJtfMinSaida(javax.swing.JFormattedTextField jtfMinSaida) {
        this.jtfMinSaida = jtfMinSaida;
    }

    public javax.swing.JTextField getJtfNomeCli() {
        return jtfNomeCli;
    }

    public void setJtfNomeCli(javax.swing.JTextField jtfNomeCli) {
        this.jtfNomeCli = jtfNomeCli;
    }

    public javax.swing.JTextField getJtfNumQuarto() {
        return jtfNumQuarto;
    }

    public void setJtfNumQuarto(javax.swing.JTextField jtfNumQuarto) {
        this.jtfNumQuarto = jtfNumQuarto;
    }

    public javax.swing.JFormattedTextField getJtfRGCli() {
        return jtfRGCli;
    }

    public void setJtfRGCli(javax.swing.JFormattedTextField jtfRGCli) {
        this.jtfRGCli = jtfRGCli;
    }

    public javax.swing.JFormattedTextField getJtfTelCli() {
        return jtfTelCli;
    }

    public void setJtfTelCli(javax.swing.JFormattedTextField jtfTelCli) {
        this.jtfTelCli = jtfTelCli;
    }

    public javax.swing.JTextField getJtfTipoQuarto() {
        return jtfTipoQuarto;
    }

    public void setJtfTipoQuarto(javax.swing.JTextField jtfTipoQuarto) {
        this.jtfTipoQuarto = jtfTipoQuarto;
    }

    public javax.swing.JFormattedTextField getJtfValorQuarto() {
        return jtfValorQuarto;
    }

    public void setJtfValorQuarto(javax.swing.JFormattedTextField jtfValorQuarto) {
        this.jtfValorQuarto = jtfValorQuarto;
    }

    public javax.swing.JFormattedTextField getJtfVlrSubTtl() {
        return jtfVlrSubTtl;
    }

    public void setJtfVlrSubTtl(javax.swing.JFormattedTextField jtfVlrSubTtl) {
        this.jtfVlrSubTtl = jtfVlrSubTtl;
    }

    public javax.swing.JTextArea getJtxaNota() {
        return jtxaNota;
    }

    public void setJtxaNota(javax.swing.JTextArea jtxaNota) {
        this.jtxaNota = jtxaNota;
    }
}
